name: Stylus Performance Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  performance-regression:
    name: Gas Regression Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Stylus Performance Check
        uses: CreativesOnchain/Stylus-Trace@v1
        with:
          tx_hash: "0xaaf333656d069068844d17f175fa5b73534c0b71599100bee2153791c3e81edc"
          rpc_url: "http://localhost:8547"
          threshold: "1.5"
